name: update

on: 
    workflow_dispatch

permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update
        run: |
          curl --verbose --no-progress-meter https://next.regexplanet.com/internal/readme.txt >./profile/README.md 

      - name: Commit
        run: |
          DIRTY=$(git diff-files --quiet; echo $?)
          echo "Dirty: $DIRTY"
          if [ $DIRTY -ne 0 ]; then
              git config user.name github-actions
              git config user.email github-actions@github.com
              git add .
              git commit -m "Updated via Github Actions on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
              git push
          fi